import { NextResponse } from "next/server";
import { governanceAuthErrorResponse } from "@/lib/auth/governance-auth-errors";
import type { Prisma } from "@prisma/client";
import prisma from "@/lib/prisma";
import { insertGovernanceAuditLog } from "@/lib/repositories/governance-audit-log-repository";
import {
  requireGovernanceCapability,
  requireReviewerAccess, requireFrameworkAssessmentAccess,
} from "@/lib/auth/truvern-governance";
import {
  buildFrameworkReleaseSnapshot,
  checksumSnapshot,
} from "@/lib/governance/framework-release";
import { signGovernancePayload } from "@/lib/governance-signature";
import { stableJson } from "@/lib/governance/framework-release";
import { findTruvernFrameworkAssessment } from "@/lib/repositories/truvern-framework-assessment-repository";
import { updateTruvernFrameworkAssessment } from "@/lib/repositories/truvern-framework-assessment-repository";
import { countTruvernAssessmentFindings } from "@/lib/repositories/truvern-assessment-finding-repository";
import { countTruvernRemediationRequests } from "@/lib/repositories/truvern-remediation-request-repository";
import { countTruvernAssessmentAttestations } from "@/lib/repositories/truvern-assessment-attestation-repository";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

type RouteContext = {
  params: Promise<{ id: string }>;
};

function parseId(value: unknown) {
  const id = Number(value);
  return Number.isInteger(id) && id > 0 ? id : null;
}

export async function POST(_request: Request, context: RouteContext) {
  try {
    const { id: rawId } = await context.params;
    const assessmentId = parseId(rawId);

    if (!assessmentId) {
      return NextResponse.json(
        { ok: false, error: "Invalid assessment id." },
        { status: 400 },
      );
    }

    const reviewer = await requireReviewerAccess();
    requireGovernanceCapability(
      reviewer,
      "report.release",
    );
    await requireFrameworkAssessmentAccess(assessmentId);

    const unresolvedFindings = await countTruvernAssessmentFindings({
      where: {
        assessmentId,
        OR: [
          {
            remediationRequired: true,
            status: { in: ["OPEN", "REMEDIATION_REQUESTED"] },
          },
          {
            attestationRequired: true,
            status: { in: ["OPEN", "REMEDIATION_REQUESTED"] },
          },
        ],
      },
    });

    const unresolvedRemediation = await countTruvernRemediationRequests({
      where: {
        finding: { assessmentId },
        status: { in: ["REQUESTED", "IN_PROGRESS", "SUBMITTED", "REJECTED"] },
      },
    });

    const unresolvedAttestations = await countTruvernAssessmentAttestations({
      where: {
        assessmentId,
        status: { in: ["REQUESTED", "SUBMITTED", "REJECTED"] },
      },
    });

    if (unresolvedFindings || unresolvedRemediation || unresolvedAttestations) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Assessment cannot be released until all remediation and attestations are resolved.",
          unresolved: {
            findings: unresolvedFindings,
            remediation: unresolvedRemediation,
            attestations: unresolvedAttestations,
          },
        },
        { status: 409 },
      );
    }

    const assessment = await findTruvernFrameworkAssessment({
      where: { id: assessmentId },
      include: {
        framework: true,
        responses: {
          include: {
            question: {
              include: {
                control: true,
              },
            },
          },
          orderBy: [{ questionId: "asc" }],
        },
        findings: {
          include: {
            remediations: {
              orderBy: [{ createdAt: "asc" }],
            },
          },
          orderBy: [{ createdAt: "asc" }],
        },
        attestations: {
          orderBy: [{ createdAt: "asc" }],
        },
      },
    });

    if (!assessment) {
      return NextResponse.json(
        { ok: false, error: "Assessment not found." },
        { status: 404 },
      );
    }

    /*

     * Immutable release finality.

     *

     * A released assessment is a historical governance record.

     * Its snapshot, checksum, seal timestamp, and release timestamp

     * must never be regenerated by a later confirmation request.

     */

    if (assessment.status === "RELEASED" || assessment.releasedAt) {
      return NextResponse.json(
        {
          ok: false,

          error: "Assessment has already been released.",

          code: "FRAMEWORK_RELEASE_ALREADY_CONFIRMED",
        },

        {
          status: 409,
        },
      );
    }

    /*
     * Strict governance lifecycle boundary.
     *
     * Release confirmation is only valid after the assessment has
     * independently transitioned into READY_FOR_RELEASE.
     *
     * confirm-release must never manufacture release readiness.
     */
    if (
      assessment.status !== "READY_FOR_RELEASE" ||
      !assessment.readyForReleaseAt
    ) {
      return NextResponse.json(
        {
          ok: false,
          error: "Only assessments ready for release can be confirmed.",
          code: "FRAMEWORK_RELEASE_NOT_READY",
          currentStatus: assessment.status,
          readyForReleaseAt: assessment.readyForReleaseAt,
        },
        {
          status: 409,
        },
      );
    }

    const snapshot = buildFrameworkReleaseSnapshot(assessment);
    const checksum = checksumSnapshot(snapshot);

    /*
     * Cryptographically authenticate the exact immutable
     * release snapshot using Truvern's active versioned
     * governance signing key.
     */
    /*
     * Canonicalize recursively before signing.
     *
     * PostgreSQL JSON/JSONB persistence does not provide an
     * object-property-order contract. Signing canonical JSON
     * makes the detached signature persistence invariant.
     */
    const canonicalSignedSnapshot = JSON.parse(stableJson(snapshot));

    const cryptographicSignature = signGovernancePayload(
      canonicalSignedSnapshot,
    );
    const releasedAt = new Date();

    const updated = await prisma.$transaction(async (tx) => {
      const releasedAssessment = await updateTruvernFrameworkAssessment(
        {
          where: { id: assessmentId },
          data: {
            status: "RELEASED",
            releasedAt,
            readyForReleaseAt: assessment.readyForReleaseAt,
            metadata: {
              ...(assessment.metadata && typeof assessment.metadata === "object"
                ? assessment.metadata
                : {}),
              governanceReleaseSnapshot: JSON.parse(
                JSON.stringify(snapshot),
              ) as Prisma.InputJsonValue,
              governanceSeal: {
                algorithm: "sha256",
                checksum,
                schema: snapshot.schema,
                sealedAt: releasedAt.toISOString(),
                version: 1,

                cryptographicSignature: {
                  algorithm: cryptographicSignature.algorithm,

                  signature: cryptographicSignature.signature,

                  signedAt: cryptographicSignature.signedAt,

                  keyId: cryptographicSignature.keyId,

                  payloadHash: cryptographicSignature.payloadHash,
                },
              },
            },
          },
        },
        tx,
      );

      await insertGovernanceAuditLog(
        {
          organizationId: assessment.organizationId,
          actorUserId: reviewer.userId ?? null,
          entityType: "TruvernFrameworkAssessment",
          entityId: String(assessmentId),
          action: "FRAMEWORK_RELEASE_CONFIRMED",
          message: "Framework assessment immutable release was confirmed.",
          metadataJson: JSON.stringify({
            checksum,
            sealedAt: releasedAt.toISOString(),
            schema: snapshot.schema,
          }),
        },
        tx,
      );

      return releasedAssessment;
    });
    return NextResponse.json({
      ok: true,
      assessment: updated,
      seal: {
        algorithm: "sha256",
        checksum,
        schema: snapshot.schema,
        sealedAt: releasedAt.toISOString(),
        version: 1,
      },
      verifyUrl: `/api/truvern/framework-assessments/${assessmentId}/verify`,
      packetUrl: `/api/truvern/framework-assessments/${assessmentId}/packet`,
    });
  } catch (error) {
    const authError = governanceAuthErrorResponse(error);
    if (authError) return authError;

    return NextResponse.json(
      {
        ok: false,
        error:
          error instanceof Error
            ? error.message
            : "Failed to confirm framework assessment release.",
      },
      { status: 500 },
    );
  }
}

